### ISSUE TITLE
Native Linux Support

### ISSUE THREAD

**Issue by Gr33nEyes** [metallicafan212/M212-Editor-Issue-Tracker#254]
I want to use editor without wrappers like Wine or Proton

**Comment by metallicafan212** [comment]
The entire editor is coded in win32 api calls, it would take years and 100s of hours of work to do that, so it will never be done.

If linux support is added back to HP2, certainly the editor will not be a part of it since the entire program is programed as a windows app above anything.

Beyond that, a lot of the subsystems added to the engine rely on windows functions or entire windows apis (for example, I recoded the editor to use Direct2D instead of GDI), which cannot be directly ported to linux.

Besides: native linux apps often perform worse than windows app running under proton or wine, which is down to compiler differences, the difficulties of using different linux libs or actually making gl perform good.

Oh yeah: only renderer available is dx9 lol, so that would have to be reimplemented in vulkan or gl (and gl just sucks tbh).

Way too much work just to say "I have a native binary". The whole game works fine under proton, my deck was getting 100 to 500fps at all times in a heavily modded game, stock game will perform much better
