### ISSUE TITLE
Issues with the launcher

### ISSUE THREAD

**Issue by fractaldichotomy** [metallicafan212/M212-Editor-Issue-Tracker#257]
When I download the M212 Editor and start the Harry Potter 2 launcher it shows me that window.dll, engine.dll and core.dll are missing istead of launching the game itself. What should I do?

**Comment by metallicafan212** [comment]
You didn't follow the directions. 

You have to install it into a clean copy of the game. Use the installer to install it please, the raw files exist only for expert modders that need raw files for a specific purpose (like localization).

There's no need to crack it, all the binaries have been recompiled from the source code, so there's no cd check even left in the code.

**Comment by fractaldichotomy** [comment]
I followed these. I created a new folder (named it M212) in Program files and copied all the game files of HP2 in this M212 folder. After this I istalled the Editor in it. So what exactly could I do wrong?

**Comment by metallicafan212** [comment]
You're missing files. You need to install a clean copy of the game from the original installer, and then use the latest installer from the document.

Join the modding server so we can communicate easier, this tracker really just exists to track features not help with installation.

https://discord.gg/DGJqb9fYET

**Comment by fractaldichotomy** [comment]
Clean copy? What do you mean? And where can I find the latest installer, what document? Are there any links? Because I downloaded the M212 Editor Setup.
I have no Discord, too complicated.

**Comment by metallicafan212** [comment]
Where the hell did you get the files from then??? I don't share the files outside of discord and the only person I let host a page for it is alexy on his HP-Games site, which just links to my google docs document. I keep it this way so that people aren't mirroring old versions or spreading it around in a way that I can't see nor help them. This is still a buggy piece of software that has many issues, since it's a 20+ year old codebase. 

Whoever shared it with you is clearly not following my instructions to "not share files or links". I made it clear in all my posts and my document to not share it please. 

Discord isn't complicated at all, takes all of 30 secs to create an account. You can even browse the entirety in your browser.

"Clean copy" refers to installing a clean copy of HP2 before installing the improved engine. The improved engine doesn't contain the game at all, just the files that were modified.

**Comment by fractaldichotomy** [comment]
Yes, I downloaded it from the Google docs document on https://hp-games.net/metallicafan212-s-harry-potter-2-en. It doesn't work?

**Comment by metallicafan212** [comment]
That's the only other authorized posting location for now.

You need to use a fresh, fully installed copy of HP2 for this, and then grab the latest installer from that page and install it into that copy.

This would be much easier to do over discord, since there's more than just me to help you there, and it's the largest modding presence for these games on the web in the first place.

**Comment by fractaldichotomy** [comment]
And where can I get that fresh, fully installed copy of HP2?

**Comment by fractaldichotomy** [comment]
Thank you, I will try it then.

**Comment by fractaldichotomy** [comment]
All it makes no sense. No fix.

**Comment by metallicafan212** [comment]
You install a copy of HP2 from a disc or disc image, andnthen you install the new game engine on top. No need for a crack or anything, and if you try to crack it, you'll find that it won't even start.

Please follow directions.

**Comment by fractaldichotomy** [comment]
The Editor deletes the Game.exe in the System folder (of the game). I think its useless to do something.

**Comment by metallicafan212** [comment]
The installer is trying to reolace the files as every binary file was recompiled for modern windows, if you don't have admin access to the game files you can't install.

Further help will not be given here, please join the discord server to get help. This issue tracker is supposed to be for editor and in game issues that are confirmed, not for debugging an installation. Installation help is what you're supposed to use the discord for.
