### ISSUE TITLE
[BUG] No tick next to the mesh browser docked option even though it is

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#64]
When the mesh browser is docked the tick icon next to the docked option does not show.
The tick icon shows for the other browsers when docked.

<img width="960" alt="dockedtick" src="https://user-images.githubusercontent.com/54454429/83903398-f7392e80-a755-11ea-8280-237ddeeb2cca.png">

**Comment by metallicafan212** [comment]
So the mesh browser never actually had a menu in the first place, I added that one just because it was the only browser without a menu. It caused the controls to move around when switching to the mesh browser.

I'll make it functional eventually, with the ability to import models right there, but for now it's literally a direct copy of the (iirc) the sound browser's menu.

**Comment by metallicafan212** [comment]
Fixed for future build
