### ISSUE TITLE
[BUG] Editor crashes when loading retail maps on times

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#80]
After opening a few retail maps the editor crashes on times with this error. 

![unknown](https://user-images.githubusercontent.com/54454429/86283109-4e58e480-bbd8-11ea-9594-1d1be4936dc8.png)

**Comment by metallicafan212** [comment]
This is caused by KWs terrible terrible naming schema. Basically: the editor looks for any old loaded actors it can use to load a new map (to help speed up load times) and it finds an actor with the same name, but their classes are different (hence KW's terrible naming problems) causing the editor to throw a fix as the in class doesn't match the out class.

**Comment by metallicafan212** [comment]
I have hacked something together that *should* help prevent the problem.

Basically: I force the editor to fully deconstruct the map by making it make a new blank level, then I garbage collect, and then load the new map.
